---
# tasks file for eclipse
- name: "Installing {{ ECLIPSE_VERSION }}"
  copy:
    src: "{{ ECLIPSE_LOCATION }}"
    dest: "{{ ECLIPSE_FOLDER_EXTRACT_LOCATION }}"
    mode: "0755"
- name: "Extracting the {{ ECLIPSE_VERSION }} files"
  unarchive:
    src: "{{ ECLIPSE_FOLDER_EXTRACT_LOCATION }}"
    dest: "{{ SW_TOOLS_LOCATION }}"
    remote_src: True
- name: "Deleting the {{ ECLIPSE_VERSION }} Zip file"
  file:
    path: "{{ ECLIPSE_FOLDER_EXTRACT_LOCATION }}"
    state: absent
