---
# tasks file for sqldeveloper
- name: "Installing {{ SQL_DEVELOPER_VERSION }}"
  copy:
    src: "{{ SQL_DEVELOPER_LOCATION }}"
    dest: "{{ SQL_DEVELOPER_FOLDER_EXTRACT_LOCATION }}"
    mode: "0755"
- name: "Extracting the {{ SQL_DEVELOPER_VERSION }} files"
  unarchive:
    src: "{{ SQL_DEVELOPER_FOLDER_EXTRACT_LOCATION }}"
    dest: "{{ SW_TOOLS_LOCATION }}"
    remote_src: True
- name: "Deleting the {{ SQL_DEVELOPER_VERSION }} Zip file"
  file:
    path: "{{ SQL_DEVELOPER_FOLDER_EXTRACT_LOCATION }}"
    state: absent
