---
# tasks file for prerequisites
- name: "Installing required packages"
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: True
    install_recommends: True
  loop: "{{ packages }}"
- name: "Creating the Folder [ {{ SW_TOOLS_LOCATION }} ] to move tool from master"
  file:
    path: "{{ SW_TOOLS_LOCATION }}"
    state: directory
    mode: "0755"
