---
# tasks file for prerequisites
- debug:
    msg: "Owner and Group level access to [ {{ user_idendity }} ]"
- name: "Installing prerequisites system packages"
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: True
    install_recommends: True
  loop: "{{ prepreq_packages }}"
- name: "Adding PPA Repository"
  apt_repository:
    repo: "{{ item }}"
    state: present
    validate_certs: False
    update_cache: True
  with_items:
    - "{{ ppa_repositories }}"
# if package has been broken in between run "apt --fix-broken install" as root
- name: "Installing required packages"
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: True
    install_recommends: True
  loop: "{{ packages }}"
- name: "Creating the Folder [ {{ SW_TOOLS_LOCATION }} ] to move tool from master"
  file:
    path: "{{ SW_TOOLS_LOCATION }}"
    state: directory
    owner: "{{ user_idendity }}"
    group: "{{ user_idendity }}"
    mode: "0777"
