---
# tasks file for filezilla
- name: "Installing {{ FILEZILLA_VERSION }}"
  copy:
    src: "{{ FILEZILLA_LOCATION }}"
    dest: "{{ FILEZILLA_FOLDER_EXTRACT_LOCATION }}"
    owner: "{{ user_idendity }}"
    group: "{{ user_idendity }}"
    mode: "0777"
- name: "Extracting the {{ FILEZILLA_VERSION }} files"
  unarchive:
    src: "{{ FILEZILLA_FOLDER_EXTRACT_LOCATION }}"
    dest: "{{ SW_TOOLS_LOCATION }}"
    remote_src: True
    owner: "{{ user_idendity }}"
    group: "{{ user_idendity }}"
    mode: "0777"
- name: "Deleting the {{ FILEZILLA_VERSION }} Zip file"
  file:
    path: "{{ FILEZILLA_FOLDER_EXTRACT_LOCATION }}"
    state: absent
